version: "3.9"
services:
  security-application-image:
    image: security-application-image
    container_name: security-application-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - spring-network

networks:
  spring-network:
